// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversation.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type AppendTurnParams struct {
	ID      uuid.UUID
	UserID  string
	TurnID  uuid.UUID
	Role    string
	Content string
}

const recentByUser = `-- name: RecentByUser :many
SELECT seq, id, user_id, turn_id, role, content, created_at
FROM (
    SELECT seq, id, user_id, turn_id, role, content, created_at
    FROM conversation
    WHERE user_id = $1
    ORDER BY seq DESC
    LIMIT $2
) recent
ORDER BY seq ASC
`

type RecentByUserParams struct {
	UserID     string
	LimitCount int32
}

type RecentByUserRow struct {
	Seq       int64
	ID        uuid.UUID
	UserID    string
	TurnID    uuid.UUID
	Role      string
	Content   string
	CreatedAt time.Time
}

// RecentByUser returns the newest @limit_count messages in chronological
// order. The inner query walks conversation_user_recent_idx backwards; the
// outer one flips the window so callers get it oldest-first for the prompt.
func (q *Queries) RecentByUser(ctx context.Context, arg RecentByUserParams) ([]RecentByUserRow, error) {
	rows, err := q.db.Query(ctx, recentByUser, arg.UserID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecentByUserRow
	for rows.Next() {
		var i RecentByUserRow
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.UserID,
			&i.TurnID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
