// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForAppendTurn implements pgx.CopyFromSource.
type iteratorForAppendTurn struct {
	rows                 []AppendTurnParams
	skippedFirstNextCall bool
}

func (r *iteratorForAppendTurn) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForAppendTurn) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].UserID,
		r.rows[0].TurnID,
		r.rows[0].Role,
		r.rows[0].Content,
	}, nil
}

func (r iteratorForAppendTurn) Err() error {
	return nil
}

func (q *Queries) AppendTurn(ctx context.Context, arg []AppendTurnParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"conversation"}, []string{"id", "user_id", "turn_id", "role", "content"}, &iteratorForAppendTurn{rows: arg})
}
