// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: focus.sql

package sqlc

import (
	"context"
)

const currentFocus = `-- name: CurrentFocus :many
SELECT phrase
FROM focus_item
WHERE user_id = $1
ORDER BY last_touched_at DESC, hits DESC, phrase
LIMIT $2::int
`

type CurrentFocusParams struct {
	UserID string
	Cap    int32
}

// CurrentFocus needs no staleness predicate: ExpireFocusSession has already
// decided whether this session exists at all, so recency here only orders the
// set, it does not retire anything from it.
func (q *Queries) CurrentFocus(ctx context.Context, arg CurrentFocusParams) ([]string, error) {
	rows, err := q.db.Query(ctx, currentFocus, arg.UserID, arg.Cap)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var phrase string
		if err := rows.Scan(&phrase); err != nil {
			return nil, err
		}
		items = append(items, phrase)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expireFocusSession = `-- name: ExpireFocusSession :execrows
DELETE FROM focus_item AS o
WHERE o.user_id = $1
  AND NOT EXISTS (
      SELECT 1
      FROM focus_item f
      WHERE f.user_id = $1
        AND f.last_touched_at > now() - make_interval(secs => $2::int)
  )
`

type ExpireFocusSessionParams struct {
	UserID      string
	IdleSeconds int32
}

// ExpireFocusSession clears a user's focus once the whole set has gone cold.
//
// All-or-nothing is what makes this a session boundary rather than a decay
// curve. Inside one long conversation a topic last mentioned forty minutes ago
// is still under discussion, so per-item expiry would quietly retire live
// context; once every item is stale there is no conversation left to belong to.
//
// It deletes rather than filters so a returning user starts genuinely clean:
// hits and first_seen_at cannot carry over from a conversation that ended days
// ago and silently outrank whatever is raised next.
func (q *Queries) ExpireFocusSession(ctx context.Context, arg ExpireFocusSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, expireFocusSession, arg.UserID, arg.IdleSeconds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pruneFocus = `-- name: PruneFocus :execrows
DELETE FROM focus_item AS o
WHERE o.user_id = $1
  AND o.phrase NOT IN (
      SELECT f.phrase
      FROM focus_item f
      WHERE f.user_id = $1
      ORDER BY f.last_touched_at DESC, f.hits DESC, f.phrase
      LIMIT $2::int
  )
`

type PruneFocusParams struct {
	UserID string
	Cap    int32
}

// PruneFocus enforces the working-memory cap. A focus set of twenty is just a
// worse short-term window, so anything past the cap is dropped by recency.
//
// The tiebreak is not decoration: one reinforcement statement stamps every row
// it touches with the same now(), so ordering by timestamp alone would make
// which item survives arbitrary.
func (q *Queries) PruneFocus(ctx context.Context, arg PruneFocusParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneFocus, arg.UserID, arg.Cap)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reinforceFocus = `-- name: ReinforceFocus :exec
INSERT INTO focus_item (user_id, phrase)
SELECT DISTINCT $1, p
FROM unnest($2::text[]) AS p
ON CONFLICT (user_id, phrase) DO UPDATE
SET hits            = focus_item.hits + 1,
    last_touched_at = now()
`

type ReinforceFocusParams struct {
	UserID  string
	Phrases []string
}

// ReinforceFocus upserts the topics the last turn was about. A phrase already
// present is refreshed and counted rather than duplicated, which is what lets a
// recurring topic outlive an incidental one without any explicit topic tracking.
//
// DISTINCT because ON CONFLICT DO UPDATE cannot touch the same row twice in one
// statement, and an extractor naming a topic twice is not an error worth failing
// the write over.
func (q *Queries) ReinforceFocus(ctx context.Context, arg ReinforceFocusParams) error {
	_, err := q.db.Exec(ctx, reinforceFocus, arg.UserID, arg.Phrases)
	return err
}
