// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: focus.sql

package sqlc

import (
	"context"
)

const getFocus = `-- name: GetFocus :one
SELECT subject
FROM focus
WHERE user_id = $1
ORDER BY last_turn_seq DESC, id DESC
LIMIT 1
`

// GetFocus returns the latest subject for a user, or no row when they have
// none. Recency is last_turn_seq DESC with id DESC as the tiebreak: extractions
// finish out of order, so a stale one may carry a higher id, but the highest
// last_turn_seq always marks the subject that is current.
func (q *Queries) GetFocus(ctx context.Context, userID string) (string, error) {
	row := q.db.QueryRow(ctx, getFocus, userID)
	var subject string
	err := row.Scan(&subject)
	return subject, err
}

const insertFocus = `-- name: InsertFocus :exec
INSERT INTO focus (user_id, subject, last_turn_seq)
VALUES ($1, $2, $3)
`

type InsertFocusParams struct {
	UserID      string
	Subject     string
	LastTurnSeq int64
}

// InsertFocus appends a subject row. Focus is append-only: every change writes
// a new row stamped with the turn it became current, never an upsert, so the
// history of subjects survives.
func (q *Queries) InsertFocus(ctx context.Context, arg InsertFocusParams) error {
	_, err := q.db.Exec(ctx, insertFocus, arg.UserID, arg.Subject, arg.LastTurnSeq)
	return err
}
