// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mid_term.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const deleteFactsForVersion = `-- name: DeleteFactsForVersion :exec
DELETE FROM mid_term_fact
WHERE user_id = $1 AND publish_version = $2::int
`

type DeleteFactsForVersionParams struct {
	UserID         string
	PublishVersion int32
}

// DeleteFactsForVersion clears a release before it is rewritten. Extraction is
// not deterministic, so a redelivered batch may yield a different number of
// facts than the attempt that died before acknowledging; replacing the release
// wholesale keeps that from leaving orphans behind, which ON CONFLICT would.
func (q *Queries) DeleteFactsForVersion(ctx context.Context, arg DeleteFactsForVersionParams) error {
	_, err := q.db.Exec(ctx, deleteFactsForVersion, arg.UserID, arg.PublishVersion)
	return err
}

const insertFact = `-- name: InsertFact :exec
INSERT INTO mid_term_fact (
    id, user_id, content, embedding, source_turn_ids,
    publish_version, fact_index, valid_from
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertFactParams struct {
	ID             uuid.UUID
	UserID         string
	Content        string
	Embedding      pgvector.Vector
	SourceTurnIds  []uuid.UUID
	PublishVersion int32
	FactIndex      int32
	ValidFrom      pgtype.Timestamptz
}

func (q *Queries) InsertFact(ctx context.Context, arg InsertFactParams) error {
	_, err := q.db.Exec(ctx, insertFact,
		arg.ID,
		arg.UserID,
		arg.Content,
		arg.Embedding,
		arg.SourceTurnIds,
		arg.PublishVersion,
		arg.FactIndex,
		arg.ValidFrom,
	)
	return err
}

const searchFacts = `-- name: SearchFacts :many
WITH probes AS (
    -- Two single-argument unnests joined on ordinality rather than one
    -- two-argument call, which sqlc's catalog cannot resolve.
    --
    -- Vectors arrive as text and are cast here rather than passed as vector[]:
    -- pgx carries a scalar vector over pgvector's text codec, but has no codec
    -- for the array type, and registering one costs a round trip on every new
    -- pooled connection.
    SELECT v.idx, v.vec::vector AS vec, t.txt
    FROM unnest($2::text[]) WITH ORDINALITY AS v(vec, idx)
    JOIN unnest($3::text[])   WITH ORDINALITY AS t(txt, idx) USING (idx)
),
dense AS (
    SELECT p.idx,
           m.id,
           m.distance,
           row_number() OVER (PARTITION BY p.idx ORDER BY m.distance) AS rank
    FROM probes p
    CROSS JOIN LATERAL (
        SELECT f.id, (f.embedding <=> p.vec) AS distance
        FROM mid_term_fact f
        WHERE f.user_id = $4
          AND f.superseded_at IS NULL
          -- Applied per probe, before fusion: retrieving the k least-unrelated
          -- facts for a question memory has nothing to say about is how an
          -- irrelevant memory gets stated back to the user as fact.
          AND (f.embedding <=> p.vec) <= $5::float8
        ORDER BY f.embedding <=> p.vec
        LIMIT $6::int
    ) m
),
lexical AS (
    SELECT p.idx,
           m.id,
           row_number() OVER (PARTITION BY p.idx ORDER BY m.score DESC) AS rank
    FROM probes p
    CROSS JOIN LATERAL (
        SELECT f.id, ts_rank(f.content_tsv, websearch_to_tsquery('english', p.txt)) AS score
        FROM mid_term_fact f
        WHERE f.user_id = $4
          AND f.superseded_at IS NULL
          AND f.content_tsv @@ websearch_to_tsquery('english', p.txt)
        ORDER BY score DESC
        LIMIT $6::int
    ) m
),
fused AS (
    SELECT r.id,
           -- The constant damps the influence of the top rank so a single
           -- retriever's first hit cannot outweigh agreement further down.
           sum(1.0 / (60 + r.rank)) AS score,
           -- 2 is the upper bound of cosine distance, so a fact the dense
           -- retriever never saw reads as maximally distant, which is exactly
           -- what it is from that retriever's point of view.
           coalesce(min(r.distance), 2) AS best_distance
    FROM (
        SELECT idx, id, rank, distance FROM dense
        UNION ALL
        SELECT idx, id, rank, NULL::float8 FROM lexical
    ) r
    GROUP BY r.id
)
SELECT f.id,
       f.content,
       f.valid_from,
       f.created_at,
       fu.score::float8         AS score,
       fu.best_distance::float8 AS best_distance
FROM fused fu
JOIN mid_term_fact f ON f.id = fu.id
ORDER BY fu.score DESC, f.created_at DESC
LIMIT $1::int
`

type SearchFactsParams struct {
	MaxResults  int32
	Vectors     []string
	Texts       []string
	UserID      string
	MaxDistance float64
	PerProbe    int32
}

type SearchFactsRow struct {
	ID           uuid.UUID
	Content      string
	ValidFrom    pgtype.Timestamptz
	CreatedAt    time.Time
	Score        float64
	BestDistance float64
}

// SearchFacts runs every probe of a decomposed query in one round trip and
// fuses the results.
//
// Two retrievers run per probe because they fail in opposite directions: dense
// search generalises over paraphrase but is weak on rare tokens, lexical search
// is the reverse. Their scores are not comparable, so they are combined by rank
// with reciprocal rank fusion rather than by any attempt to calibrate the two
// scales against each other.
//
// A fact surfaced by several probes accumulates several reciprocal-rank terms
// and rises accordingly, which is the behaviour we want: agreement across
// independent probes is evidence.
func (q *Queries) SearchFacts(ctx context.Context, arg SearchFactsParams) ([]SearchFactsRow, error) {
	rows, err := q.db.Query(ctx, searchFacts,
		arg.MaxResults,
		arg.Vectors,
		arg.Texts,
		arg.UserID,
		arg.MaxDistance,
		arg.PerProbe,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchFactsRow
	for rows.Next() {
		var i SearchFactsRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.ValidFrom,
			&i.CreatedAt,
			&i.Score,
			&i.BestDistance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
