// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mid_term_memory.sql

package sqlc

import (
	"context"

	pgvector "github.com/pgvector/pgvector-go"
)

const searchMemory = `-- name: SearchMemory :many
SELECT
    user_id,
    publish_version,
    summary,
    start_seq,
    end_seq,
    (1 - (embedding <=> $1))::float8 AS similarity
FROM mid_term_memory
WHERE user_id = $2
ORDER BY embedding <=> $1
LIMIT $3
`

type SearchMemoryParams struct {
	Embedding pgvector.Vector
	UserID    string
	LimitRows int32
}

type SearchMemoryRow struct {
	UserID         string
	PublishVersion int32
	Summary        string
	StartSeq       int64
	EndSeq         int64
	Similarity     float64
}

// SearchMemory returns the summaries most similar to the query embedding,
// always scoped to one user. similarity is cosine similarity: the <=> operator
// yields cosine distance, so 1 - distance restores the [0,1] scale where 1 is
// identical. The caller applies a minimum-similarity threshold.
func (q *Queries) SearchMemory(ctx context.Context, arg SearchMemoryParams) ([]SearchMemoryRow, error) {
	rows, err := q.db.Query(ctx, searchMemory, arg.Embedding, arg.UserID, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMemoryRow
	for rows.Next() {
		var i SearchMemoryRow
		if err := rows.Scan(
			&i.UserID,
			&i.PublishVersion,
			&i.Summary,
			&i.StartSeq,
			&i.EndSeq,
			&i.Similarity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMemory = `-- name: UpsertMemory :exec
INSERT INTO mid_term_memory
    (user_id, publish_version, summary, embedding, start_seq, end_seq)
VALUES
    ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, publish_version) DO UPDATE SET
    summary    = EXCLUDED.summary,
    embedding  = EXCLUDED.embedding,
    start_seq  = EXCLUDED.start_seq,
    end_seq    = EXCLUDED.end_seq
`

type UpsertMemoryParams struct {
	UserID         string
	PublishVersion int32
	Summary        string
	Embedding      pgvector.Vector
	StartSeq       int64
	EndSeq         int64
}

// UpsertMemory writes (or overwrites) the mid-term summary for one release. The
// composite key (user_id, publish_version) makes a replayed or stale write an
// in-place update, never a duplicate row.
func (q *Queries) UpsertMemory(ctx context.Context, arg UpsertMemoryParams) error {
	_, err := q.db.Exec(ctx, upsertMemory,
		arg.UserID,
		arg.PublishVersion,
		arg.Summary,
		arg.Embedding,
		arg.StartSeq,
		arg.EndSeq,
	)
	return err
}
