// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Conversation struct {
	Seq            int64
	ID             uuid.UUID
	UserID         string
	TurnID         uuid.UUID
	Role           string
	Content        string
	CreatedAt      time.Time
	PublishStatus  string
	PublishedAt    pgtype.Timestamptz
	PublishVersion int32
}
