// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	pgvector "github.com/pgvector/pgvector-go"
)

type Conversation struct {
	Seq            int64
	ID             uuid.UUID
	UserID         string
	TurnID         uuid.UUID
	Role           string
	Content        string
	CreatedAt      time.Time
	PublishStatus  string
	PublishedAt    pgtype.Timestamptz
	PublishVersion int32
	Stage          string
	ClaimedAt      pgtype.Timestamptz
}

type Focu struct {
	ID          int64
	UserID      string
	Subject     string
	LastTurnSeq int64
	CreatedAt   time.Time
}

type MidTermMemory struct {
	UserID         string
	PublishVersion int32
	Summary        string
	Embedding      pgvector.Vector
	StartSeq       int64
	EndSeq         int64
	CreatedAt      time.Time
}
