// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Conversation struct {
	Seq            int64
	ID             uuid.UUID
	UserID         string
	TurnID         uuid.UUID
	Role           string
	Content        string
	CreatedAt      time.Time
	PublishStatus  string
	PublishedAt    pgtype.Timestamptz
	PublishVersion int32
}

type MidTermFact struct {
	ID             uuid.UUID
	UserID         string
	Content        string
	Embedding      pgvector.Vector
	SourceTurnIds  []uuid.UUID
	PublishVersion int32
	FactIndex      int32
	ValidFrom      pgtype.Timestamptz
	CreatedAt      time.Time
	SupersededAt   pgtype.Timestamptz
	ContentTsv     interface{}
}
